const Sdata = {
    shopItems: [
      {
        id: 1,
        cover: "./images/arrivals/arrivals1.png",
        name: "iPhone 13 PRO",
        category: "Smartphone",
        brandName: "Apple",
        price: 800,
        stars: 4,
        discount: "25",
        pieces: 80,
      },
      {
        id: 2,
        cover: "./images/arrivals/arrivals2.png",
        name: "Samsung Galaxy S22",
        category: "Smartphone",
        brandName: "Samsung",
        price: 599,
        stars: 3,
        discount: "25",
        pieces: 20,
      },
      {
        id: 3,
        cover: "./images/arrivals/arrivals2.png",
        name: "Vivo android one",
        category: "Smartphone",
        brandName: "Vivo",
        price: 120,
        stars: 1,
        discount: "10",
        pieces: 10,
      },
      {
        id: 4,
        cover: "./images/arrivals/arrivals1.png",
        name: "Mapple Earphones",
        category: "Smartphone",
        brandName: "Samsung",
        price: 180,
        stars: 5,
        discount: "25",
        pieces: 10,
      },
      {
        id: 5,
        cover: "./images/arrivals/arrivals2.png",
        name: "Vivo android one",
        category: "Smartphone",
        brandName: "Apple",
        price: 120,
        stars: 3,
        discount: "10",
        pieces: 10,
      },
      {
        id: 6,
        cover: "./images/arrivals/arrivals3.png",
        name: "Sony Light",
        category: "Smartphone",
        brandName: "Oppo",
        price: 20,
        stars: 4,
        discount: "50",
        pieces: 10,
      },
      {
        id: 7,
        cover: "./images/arrivals/arrivals1.png",
        name: "Iphone",
        category: "PC",
        brandName: "Samsung",
        price: 999,
        stars: 4,
        discount: "10",
        pieces: 10,
      },
      {
        id: 8,
        cover: "./images/arrivals/arrivals2.png",
        name: "Ceats wireless earphone",
        category: "PC",
        brandName: "Samsung",
        price: 80,
        stars: 4,
        discount: "20",
        pieces: 10,
      },
      {
        id: 9,
        cover: "./images/arrivals/arrivals3.png",
        name: "Redimi Phone",
        category: "PC",
        brandName: "Redmi",
        price: 400,
        stars: 4,
        discount: "20",
        pieces: 10,
      },
      {
        id: 10,
        cover: "./images/arrivals/arrivals3.png",
        name: "Xeats Bluetooth earphones",
        category: "Tablet",
        brandName: "Samsung",
        price: 60,
        stars: 4,
        discount: "5",
        pieces: 10,
      },
      {
        id: 11,
        cover: "./images/arrivals/arrivals2.png",
        name: "Airpod",
        category: "Tablet",
        brandName: "Apple",
        price: 120,
        stars: 3,
        discount: "10",
        pieces: 10,
      },
      {
        id: 12,
        cover: "./images/arrivals/arrivals1.png",
        name: "Silver Cap",
        category: "Tablet",
        brandName: "Xiaomi",
        price: 5,
        stars: 5,
        discount: "2",
        pieces: 10,
      },
      {
        id: 13,
        cover: "./images/arrivals/arrivals1.png",
        name: "Silver Cap",
        category: "Smartphone",
        brandName: "Xiaomi",
        price: 5,
        stars: 5,
        discount: "2",
        pieces: 10,
      },
    ],
}
export default Sdata
  